### ISSUE TITLE
Document how to increase the plugin log level to debug

### ISSUE THREAD

**Issue by smkent** [matrix-org/matrix-synapse-ldap3#21]
This is the synapse config I used to increase the log level for the LDAP plugin:

```
version: 1

formatters:
  precise:
   format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s- %(message)s'

filters:
  context:
    (): synapse.util.logcontext.LoggingContextFilter
    request: ""

handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: precise
    filename: /path/to/synapse/homeserver.log
    maxBytes: 104857600
    backupCount: 10
    filters: [context]
    level: DEBUG
  console:
    class: logging.StreamHandler
    formatter: precise
    filters: [context]

loggers:
    synapse:
        level: INFO

    synapse.storage.SQL:
        level: INFO

    ldap3:
        level: DEBUG

    ldap_auth_provider:
        level: DEBUG

root:
    level: INFO
    handlers: [file, console]
```

List of changes from the default generated config:
* Set `handlers -> file -> level` to `DEBUG`
* Added the `loggers -> ldap3` and `loggers -> ldap_auth_provider` sections, both with `level: DEBUG`

This should be documented in the repository somewhere, perhaps in the main README.
