### ISSUE TITLE
socket connection error: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by ChromoX** [matrix-org/matrix-synapse-ldap3#32]
I've been trying to get LDAP authentication setup with my Matrix server. Using the config below I get the following error messages. I have verified that the ldap server name resolves and that I can hit the LDAP service from the Synapse server. I also see no logs on the LDAP server that show that matrix has tried to connect. Any help would be greatly appreciated.

Package: python-matrix-synapse-ldap3 v0.1.2.

```
password_providers:
    - module: "ldap_auth_provider.LdapAuthProvider"
      config:
        enabled: true
        uri: "ldap://<hostname or ip>:389"
        start_tls: false # I've tried with true as well.
        base: "<base>"
        attributes:
           uid: "uid"
           mail: "mail"
           name: "givenName"
        bind_dn: "<bind dn>"
        bind_password: "<bind pass>"
        filter: "(objectClass=posixAccount)"

handlers:
  file:
    level: DEBUG

loggers:
  ldap3:
    level: DEBUG
  ldap_auth_provider:
    level: DEBUG
```

```
2017-06-30 06:13:29,341 - synapse.handlers.auth - 66 - INFO -  - Extra password_
providers: [<ldap_auth_provider.LdapAuthProvider object at 0x7f25cbc0a250>]

2017-06-30 06:13:52,817 - ldap_auth_provider - 403 - WARNING - POST-1 - Error du
ring LDAP authentication: socket connection error: [Errno -2] Name or service no
t known
```
