### ISSUE TITLE
Can't seem to get the module working at all on Ubuntu 18.04

### ISSUE THREAD

**Issue by ErrorProne** [matrix-org/matrix-synapse-ldap3#65]
Hi,

I'm sorry for opening a ticket for what maybe a trivial problem but I'm stuck for hours now. Basically this is a testsetup and I'm trying to get it working against our Active Directory.

I've an Ubuntu 18.04 with these packages installed from the matrix repository: https://matrix.org/packages/debian/

```
ii  matrix-synapse-ldap3                  0.1.2-1                           all          LDAP auth provider for the Matrix homeserver
ii  matrix-synapse-py3                    1.1.0+bionic1                     amd64        Open federated Instant Messaging and VoIP server
```

The config looks like this
```
password_providers:
 - module: "ldap_auth_provider.LdapAuthProvider"
   config:
     enabled: true
     uri: "ldap://dc1.lab"
     start_tls: false
     mode: "search"
     base: "dc=lab"
     attributes:
       uid: "cn"
       mail: "userPrincipalName"
       name: "givenName"
     bind_dn: "CN=Matrix Synapse,OU=Service Accounts,DC=lab"
     bind_password: "xxx"
```

The log config
```
loggers:
    synapse:
        level: DEBUG

    synapse.storage.SQL:
        level: INFO
    ldap3:
        level: DEBUG
    ldap_auth_provider:
        level: DEBUG
```

However when I'm trying a login the module does not seem to kick in at all:
```
2019-07-15 16:23:13,638 - synapse.rest.client.v1.login - 175 - INFO - POST-3- Got login request with identifier: {'type': 'm.id.thirdparty', 'medium': 'email', 'address': 'test@lab'}, medium: 'email', address: 'test@lab', user: None
2019-07-15 16:23:13,639 - synapse.storage.txn - 394 - DEBUG - POST-3- [TXN START] {get_user_id_by_threepid-2d}
2019-07-15 16:23:13,642 - synapse.storage.txn - 456 - DEBUG - POST-3- [TXN END] {get_user_id_by_threepid-2d} 0.003613 sec
2019-07-15 16:23:13,643 - synapse.rest.client.v1.login - 224 - WARNING - POST-3- unknown 3pid identifier medium email, address 'test@lab'
2019-07-15 16:23:13,646 - synapse.http.server - 79 - INFO - POST-3- <XForwardedForRequest at 0x7f20b8608fd0 method='POST' uri='/_matrix/client/r0/login' clientproto='HTTP/1.0' site=8008> SynapseError: 403 -
```

Also I don't see any connections in the AD log.

Does anyone have any pointers?

**Comment by ErrorProne** [comment]
Ok, so I hope I get this right:
I simply assumed the Active Directory  UPN style in form of an email address would work. Looking at the code Synapse tries to trigger a check_3pid_auth which is defined here https://github.com/matrix-org/matrix-synapse-ldap3/blob/1ace52a64a5acb0b901c287edbcd402447acebc9/ldap_auth_provider.py#L191 but not in the current releases?

So I've switched to the normal username, John Doe which got me to the point where the module started to work, didn't found the user in the local db and tried to register it:

```
2019-07-15 17:42:33,480 - ldap_auth_provider - 163 - DEBUG - - ldap registration filter: (cn=John Doe)
2019-07-15 17:42:33,487 - synapse.http.server - 79 - INFO - - <XForwardedForRequest at 0x7f02e62e0fd0 method='POST' uri='/_matrix/client/r0/login' clientproto='HTTP/1.0' site=8008> SynapseError: 400 - User ID can only contain characters a-z, 0-9, or '=_-./'
```

This looks like trouble if the user id can't contain white spaces or similiar.

**Comment by ErrorProne** [comment]
Based on the above, for other AD users, this should get your working:
```
     attributes:
       uid: "samaccountname"
       mail: "userPrincipalName"
       name: "givenName"
```
However the limit here is that only the samaccountname is valid for the login.
