### ISSUE TITLE
LDAP filter not been honored

### ISSUE THREAD

**Issue by pabelenda** [matrix-org/matrix-synapse-ldap3#68]
I've a synapse server running matrix-synapse-ldap3 (0.1.3) along with matrix-synapse (1.2.1).

The LDAP configuration is as follows:

```
password_providers:
  - module: "synapse.util.ldap_auth_provider.LdapAuthProvider"
    config:
       enabled: true
       uri: "ldap.mydomain.com"
       start_tls: false
       base: "ou=People,dc=mydomain,dc=com"
       attributes:
           uid: "uid"
           mail: "mail"
           name: "givenName"
       filter: "(&(mail=*@mydomain.com)(!(loginShell=/bin/false))(|(employeeType=type1)(employeeType=type2)(employeeType=type3)))"
```

What is happening is that people with `employeeType` type4 is been able to login into the server and that shouldn't be the case at all, as the `OR` conditional part will be `False`, making the whole statement to be `False`.

Am I missing something? Is there something wrong on the module side?

Many thanks in advance for taking a look.
