### ISSUE TITLE
LDAP registration failed, no result.

### ISSUE THREAD

**Issue by danptr** [matrix-org/matrix-synapse-ldap3#74]
The configuration I am using. I can see that my credentials are correct and the LDAP connection works since synapse is able to bind to my LDAP user. However, login still does not work with the user. Could someone point me in the right direction?
```
config:
      enabled: true
      mode: "search"
      uri: "ldaps://abc.com:636"
      start_tls: true
      base: "ou=users,o=abc,c=com"
      attributes:
        uid: "uid"
        mail: "mail"
        name: "cn"
      bind_dn: "cn=admin,ou=users,o=abc,c=com"
      bind_password: "password"
      filter: ""
```

The error messages I get:
```
synapse.rest.client.v1.login - 176 - INFO - POST-6 - Got login request with identifier: {'type': 'm.id.user', 'user': 'uname'}, medium: None, address: None, user: None
User authenticated against LDAP server: ldaps://abc.com:636 - ssl - user: cn=uname,ou=users,o=abc,c=com - not lazy - bound - open - <local: 172.18.0.4:46946 - remote: xxx.xxx.xx.xx:636> - tls not started - listening - SyncStrategy - internal decoder
synapse.storage._base - 496 - WARNING -  - Starting db txn 'get_users_by_id_case_insensitive' from sentinel context
synapse.storage._base - 535 - WARNING -  - Starting db connection from sentinel context: metrics will be lost
synapse.handlers.auth - 528 - WARNING -  - Attempted to login as @uname:matrix.abc.com but they do not exist
ldap_auth_provider - 208 - WARNING -  - LDAP registration failed, no result.
synapse.storage._base - 496 - WARNING -  - Starting db txn 'get_users_by_id_case_insensitive' from sentinel context
synapse.storage._base - 535 - WARNING -  - Starting db connection from sentinel context: metrics will be lost
synapse.handlers.auth - 528 - WARNING -  - Attempted to login as @uname:matrix.abc.com but they do not exist
synapse.http.server - 80 - INFO -  - <XForwardedForRequest at 0x7f3ea57603d0 method='POST' uri='/_matrix/client/r0/login' clientproto='HTTP/1.0' site=8008> SynapseError: 403 - Invalid password
```

**Comment by awesome-michael** [comment]
Have the same error with a slightly different config. 

In my opinion the error happens between after line 149 where the ldap provider tries to register the user (that exists in ldap but not in synapse) at synapse. I don't get how the results from the search request for the users details in line 166 are returned so they are usable in line 176. The result seems to be empty, hence the error "LDAP registration failed, no result."

Could someone have a look into that bit?

```
password_providers:
    - module: "ldap_auth_provider.LdapAuthProvider"
      config:
        enabled: true
        mode: "search"
        uri: "ldap://ldap:389"
        start_tls: false
        base: "dc=example,dc=org"
        attributes:
           uid: "uid"
           mail: "mail"
           name: "cn"
        bind_dn: "cn=admin,dc=example,dc=org"
        bind_password: "password"
        filter: "(objectClass=inetOrgPerson)"
```

logs

```
ldap_auth_provider - 91 - DEBUG - POST-3 - Attempting LDAP connection with ldap://ldap:389
ldap_auth_provider - 342 - DEBUG -  - Established LDAP connection in search mode: ldap://openldap:389 - cleartext - user: cn=admin,dc=example,dc=org - not lazy - unbound - closed - <no socket> - tls not started - not listening - SyncStrategy - internal decoder
synapse.metrics - 462 - INFO -  - Collecting gc 1
ldap_auth_provider - 375 - DEBUG -  - LDAP search filter: (&(uid=tester)(objectClass=inetOrgPerson))
ldap_auth_provider - 393 - DEBUG -  - LDAP search found dn: uid=tester,ou=users,dc=example,dc=org
ldap_auth_provider - 287 - DEBUG -  - Established LDAP connection in simple bind mode: ldap://ldap:389 - cleartext - user: uid=tester,ou=users,dc=example,dc=org - not lazy - unbound - closed - <no socket> - tls not started - not listening - SyncStrategy - internal decoder
ldap_auth_provider - 301 - DEBUG -  - LDAP Bind successful in simple bind mode.
ldap_auth_provider - 119 - DEBUG -  - LDAP auth method authenticated search returned: True (conn: ldap://ldap:389 - cleartext - user: uid=tester,ou=users,dc=example,dc=org - not lazy - bound - open - <local: xxx - remote: xxx:389> - tls not started - listening - SyncStrategy - internal decoder)
ldap_auth_provider - 133 - INFO -  - User authenticated against LDAP server: ldap://ldap:389 - cleartext - user: uid=tester,ou=users,dc=example,dc=org - not lazy - bound - open - <local: xxx - remote: xxx:389> - tls not started - listening - SyncStrategy - internal decoder
synapse.storage._base - 497 - WARNING -  - Starting db txn 'get_users_by_id_case_insensitive' from sentinel context
synapse.storage._base - 536 - WARNING -  - Starting db connection from sentinel context: metrics will be lost
synapse.handlers.auth - 528 - WARNING -  - Attempted to login as @tester:example.org but they do not exist
ldap_auth_provider - 163 - DEBUG -  - ldap registration filter: (&(uid=tester)(objectClass=inetOrgPerson))
ldap_auth_provider - 208 - WARNING -  - LDAP registration failed, no result.
synapse.http.server - 80 - INFO -  - <XForwardedForRequest at 0x7faccfb2dfd0 method='POST' uri='/_matrix/client/r0/login' clientproto='HTTP/1.1' site=8008> SynapseError: 403 - Invalid password
```
