### ISSUE TITLE
Windows AD Login failed

### ISSUE THREAD

**Issue by douglas-lee** [matrix-org/matrix-synapse-ldap3#9]
LDAP was worked fine, but user login has failed. Cause matrix will give ad the username format: @username@domain.com:homeserver to Windows AD. They, it a wrong name, ad will return: the user is not exist. How to set the username just what I fill?

**Comment by mweinelt** [comment]
Which version of `matrix-synapse-ldap3` are you running currently? Specifically to the actual commit would be good to know. And maybe dump some redacted synapse log for the ldap handler.

**Comment by jkolo** [comment]
I needed to set up additional user, which is used to search users in AD.
Below mine configuration, which works with AD (SAMBA4). 

```yaml
password_providers:
   - module: "ldap_auth_provider.LdapAuthProvider"
     config:
        enabled: true
        uri: "ldap://****.*********.pl:389"
        start_tls: false
        base: "cn=Users,dc=*********,dc=pl"
        attributes:
           uid: "sAMAccountName"
           mail: "mail"
           name: "givenName"
        bind_dn: "cn=matrix,cn=Users,dc=*********,dc=pl"
        bind_password: "******************************************************"
        filter: "(&(objectclass=organizationalPerson)(|(memberof=CN=Matrix Users,CN=Users,DC=*********,DC=pl)(primaryGroupID=1148)))"
```

Additionally, I had to filter the query results. Corresponding changes in PR #8
