### ISSUE TITLE
Using LDAP base without ou, only o

### ISSUE THREAD

**Issue by Paule2020** [matrix-org/matrix-synapse-ldap3#98]
Hello,
is it possible to use ldap-out without selecting an ou, like:

```
 password_providers:
    # Example config for an LDAP auth provider
    - module: "ldap_auth_provider.LdapAuthProvider"
      config:
        enabled: true
        #mode: "search"
        uri: "ldap://server-ip
        start_tls: false
        #base: "ou=teacher, o=school"
        base: "o=school"
        attributes:
           uid: "cn"
           mail: "email"
           name: "givenName"
           bind_dn: "cn=admin,o=server" (cn=paule2020 doesn't work aswell...)
           bind_passwortd : "password"
```
           
```ldap_auth_provider - 92 - DEBUG - POST-136 - Attempting LDAP connection with ldap://server-ip:389
2020-08-17 19:06:30,263 - ldap_auth_provider - 364 - DEBUG -  - Established LDAP connection in simple bind mode: ldap://server-ip:389 - cleartext - user: cn=paule2020 ,o=school- not lazy - unbound - closed - <no socket> - tls not started - not listening - SyncStrategy - internal decoder
2020-08-17 19:06:33,284 - ldap_auth_provider - 384 - INFO -  - Binding against LDAP failed for 'cn=paule2020 ,o=school' failed: invalidCredentials
2020-08-17 19:06:33,294 - ldap_auth_provider - 106 - DEBUG -  - LDAP authentication method simple bind returned: False (conn: None)
2020-08-17 19:06:33,297 - synapse.storage.database - 515 - WARNING -  - Starting db txn 'get_users_by_id_case_insensitive' from sentinel context
2020-08-17 19:06:33,300 - synapse.storage.database - 553 - WARNING -  - Starting db connection from sentinel context: metrics will be lost
2020-08-17 19:06:33,304 - synapse.storage.database - 515 - WARNING -  - Starting db txn 'get_user_deactivated_status' from sentinel context
2020-08-17 19:06:33,305 - synapse.storage.database - 553 - WARNING -  - Starting db connection from sentinel context: metrics will be lost
2020-08-17 19:06:33,308 - synapse.handlers.auth - 837 - WARNING -  - Failed password login for user @paule2020:matrix-server...
2020-08-17 19:06:33,309 - synapse.http.server - 74 - INFO -  - <XForwardedForRequest at 0x7f4565dcb550 method='POST' uri='/_matrix/client/r0/login' clientproto='HTTP/1.0' site=8008> SynapseError: 403 - Invalid password```

When I use this line base: "ou=teacher, o=school", auth with LDAP works fine, but without an ou the error you see above occurs.
